name: Unzip Chinese Font Asset

on:
  workflow_dispatch:
  
  push:
    branches: [ master ]
    paths:
      - 'assets/tmpchinesefont.7z'

jobs:
  unzip:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install 7z
      run: sudo apt-get install p7zip-full -y

    - name: Extract 7z
      run: 7z x -y ./assets/tmpchinesefont.7z -o./assets